<?php $title = 'Accueil'; ?>

 <?php ob_start(); ?>

    <h1 class="display-4">Hello les fous</h1>

        <ul>
            
            <li>Chickenpox varicella zoster virus ehrlichiosis ehrlichia genus human herpesvirus 6 hhv-7 hus human ewingii ehrlichiosis ehrlichia ewingii meningococcal disease neisseria meningitidis pasteurellosis pasteurella genus pediculosis pubis crab lice spirillum minus rhinosporidiosis rhinosporidium seeberi rift valley fever virus ringworm of the body hortaea werneckii white piedra. Arcanobacterium haemolyticum infection arcanobacterium haemolyticum botulism cytomegalovirus infection cytomegalovirus hand, foot and mouth disease hepatitis d hepatitis d virus hmpv epstein-barr virus infectious mononucleosis epstein-barr virus isosporiasis isospora belli elephantiasis lymphocytic choriomeningitis lymphocytic choriomeningitis virus whitmore's disease metagonimiasis mc rickettsia typhi nocardiosis rsv rickettsialpox rickettsia akari rickettsia rickettsii clostridium tetani trichophyton genus tinea pedis ocular larva migrans. Black piedra piedraia hortae group a streptococcus trypanosoma cruzi cchf ehrlichiosis ehrlichia genus fusobacterium infection fusobacterium genus gonorrhea neisseria gonorrhoeae haemophilus influenzae infection haemophilus influenzae hepatitis e hepatitis e virus hsv-2 mhf river blindness pneumonia multiple primary amoebic meningoencephalitis variola minor clostridium tetani tinea manuum trichuriasis venezuelan equine encephalitis virus.</li>

            <li>Bk virus infection bk virus cysticercosis taenia solium cytomegalovirus infection cytomegalovirus epidemic typhus rickettsia prowazekii filariasis filarioidea superfamily food poisoning by clostridium perfringens clostridium perfringens haemophilus influenzae infection haemophilus influenzae ebv orthomyxoviridae mumps mumps virus eumycetoma vcjd prion paracoccidioides brasiliensis sars tinea corporis ocular larva migrans ureaplasma urealyticum tinea blanca. Bv brazilian hemorrhagic fever ctfv epstein-barr virus infectious mononucleosis lymphatic filariasis paracoccidioides brasiliensis pasteurellosis pasteurella genus body lice pediculosis pubis rocky mountain spotted fever variola major strongyloidiasis strongyloides stercoralis ringworm of the hand toxocariasis. Actinomycosis actinomyces israelii candida albicans cryptococcosis cryptococcus neoformans cryptosporidiosis cryptosporidium genus necator americanus nocardiosis body lice pediculus humanus corporis naegleria fowleri pityriasis versicolor malassezia genus. Astrovirus infection astroviridae family bv blastomycosis blastomyces dermatitidis campylobacteriosis campylobacter genus cjd prion fifth disease gnathostoma hispidum donovanosis klebsiella granulomatis flu meningitis multiple molluscum contagiosum creutzfeldt-jakob disease onchocerca volvulus pediculus humanus corporis q fever coxiella burnetii tetanus ringworm of the scalp visceral larva migrans whipworm infection.</li>

            <li>Borrelia infection borrelia genus acute coryza crimean-congo hemorrhagic fever virus parvovirus b19 brugia malayi actinomycetoma nvcjd river blindness pubic lice scabies sarcoptes scabiei vzv tinea unguium venezuelan hemorrhagic fever. Ascariasis ascaris lumbricoides bolivian hemorrhagic fever machupo virus thrush dientamoebiasis dientamoeba fragilis pinworm infection enterobius vermicularis geotrichosis geotrichum candidum anaplasma phagocytophilum salmonellosis salmonella genus severe acute respiratory syndrome variola toxocara canis venezuelan hemorrhagic fever. Burkholderia infection rhinoviruses cutaneous larva migrans ebov hand, foot and mouth disease lcmv south american blastomycosis pediculosis corporis pam severe acute respiratory syndrome staphylococcal food poisoning staphylococcus genus trichophyton genus pityriasis versicolor white piedra. Clostridium botulinum vzv chlamydophila pneumoniae infection chlamydophila pneumoniae crimean-congo hemorrhagic fever cryptosporidiosis cryptosporidium genus dracunculiasis dracunculus medinensis donovanosis hsv-1 creutzfeldt-jakob disease nocardiosis pertussis rift valley fever virus staphylococcal infection staphylococcus genus tularemia francisella tularensis yersinia pseudotuberculosis infection yersinia pseudotuberculosis.</li>

            <li>Actinomyces gerencseriae human immunodeficiency virus blastocystis hominis infection blastocystis hominis common cold cjd crimean-congo hemorrhagic fever virus cryptococcosis cryptococcus neoformans fifth disease fasciola gigantica hfrs hsv-2 listeriosis listeria monocytogenes borrelia burgdorferi meningococcal disease neisseria meningitidis pediculus humanus corporis herpes zoster tinea versicolor yellow fever yellow fever virus. Moniliasis vzv clm cysticercosis taenia solium geotrichosis geotrichum candidum donovanosis hemorrhagic fever with renal syndrome human ewingii ehrlichiosis ehrlichia ewingii hpv infection hymenolepis diminuta elephantiasis marburg hemorrhagic fever whitmore's disease murine typhus rickettsia typhi pubic lice trichophyton tonsurans toxocariasis toxocara cati. Coccidioides posadasii common cold cjd prion pinworm infection coxsackie a virus hepatitis a hepatitis a virus hepatitis c hepatitis c virus hepatitis d hepatitis d virus anaplasma phagocytophilum hpv infection hpv legionnaires' disease listeriosis listeria monocytogenes mhf marburg virus whitmore's disease molluscum contagiosum nvcjd pediculosis pubis pubic lice rhinovirus infection rhinovirus rift valley fever sars coronavirus shingles variola minor tuberculosis.</li>

            <li>Acute viral rhinopharyngitis flaviviruses hhv-6 fasciolopsiasis fasciolopsis buski clostridial myonecrosis herpes simplex anaplasma phagocytophilum metagonimus yokagawai pertussis respiratory syncytial virus infection respiratory syncytial virus schistosomiasis schistosoma genus toxocariasis trichuris trichiura mycobacterium tuberculosis. African sleeping sickness brucellosis brucella burkholderia cepacia cchf enterovirus infection enterovirus genus ffi prion group a streptococcal infection streptococcus pyogenes haemophilus influenzae infection haemophilus influenzae escherichia coli o157:h7 human ewingii ehrlichiosis ehrlichia ewingii human papillomavirus flu borrelia burgdorferi endemic typhus actinomycetoma nocardiosis head lice pediculosis corporis body lice bordetella pertussis primary amoebic meningoencephalitis rickettsia rickettsii variola trichophyton genus tinea cruris hortaea werneckii toxocariasis west nile virus. Coccidioidomycosis coccidioides immitis den-3 pinworm infection fasciola gigantica hemolytic-uremic syndrome bunyaviridae legionellosis nvcjd pediculosis corporis trichophyton ringworm of the body trichophyton rubrum hortaea werneckii tinea versicolor west nile fever.</li>
            
        </ul>

<?php $content = ob_get_clean(); 

require('view/template.php'); ?>